Locked the jwt-simple to 0.5.3 as it was installing 0.5.6 and causing issues.
When 0.5.6 was installing we were getting errors regarding [TypeError: base64 is not a function]